algorithm = {
    #-------C-letters-------
        "A": "ooDw23)s",
        "B": "3gj^ds(#@)",
        "C": "PP0d-s#2hHh",
        "E": ")dww2B$OWID",
        "F": "88/*s**wqd",
        "G": "#*21$&3f",
        "H": "Oi2DD!J",
        "I": "#e@ds11",
        "J": "-2-1_RR3",
        "K": "+LtBBsc",
        "L": "DS2499)",
        "M": "oo2D##ub",
        "N": "A(*)D",
        "O": "IUrg2F",
        "Q": "23##(9)",
        "R": "#TubNw$",
        "S": "PO$1y^S3",
        "T": "p#2441Hb",
        "U": "09F)(@sb",
        "V": "Jygh637",
        "W": "01V?c%z",
        "X": "1",
        "Y": "@d##4",
        "Z": "%",
    #-------numbers-------
        '1':'9SO#^&&gsOb*',
        '2':'PE!!2O0%$#%$',
        '3':'-O1_#23%_#-',
        '4':'*2O2(sCCx',
        '5':'1~`ODDsLLpb',
        '6':'+`WE~s~O=d',
        '7':'3O1',
        '8':'+O',
        '9':'OU7s',
        '0':'~!O#Q',
    #------S-letters-------
        'a':'%esOs@KrD',
        'b':'-)2O2F',
        'c':'POo@r%',
        'd':'22}!Odcc',
        'e':'/#O#130F',
        'f':'12`O>>L',
        'g':'>=O+',
        'h':'1O',
        'i':'-13Op',
        'j':'0V',
        'k':'03OpbiO',
        'l':'pBVOE**2O',
        'm':'}Oee2',
        'n':'eQO8b*',
        'o':'dpsO"w2O',
        'p':'/w/sO/ggbO',
        'q':'n&O!@O',
        'r':'IC0OO',
        's':'@objv7()O',
        't':'JuObIO(',
        'u':'O)pU&2FFCO',
        'v':'Pew/O0c',
        'w':'j}l@rOEO',
        'x':')O',
        'y':'PFc9O',
        'z':'O'
    }